### ISSUE TITLE
SMBIOS wrong

### ISSUE THREAD

**Issue by crlink271986** [joepool/Hackintosh-HP-Z420-OpenCore#10]
hi just saying the config plist smbios is wrong for this computer you have it set to imac 14,2 (yes it is a haswell but it's not a Xeon Haswell the correct model you need is the 2013 Mac Pro (Mac Pro 6,1) this computer has a very similar Xeon (E5-1620) this will fix install/boot issues in both clover and OC for the Z420

**Comment by joepool** [comment]
If you read the readme document you will see that this is an open core efi, I have only included the clover as its an alternative and it works, if there is any problems with opencore. In the opencore efi the smbios is correct as you can see [here](https://github.com/joepool/Hackintosh-HP-Z420-OpenCore/blob/1a89df5b4ee731319ef5dc0306da493e3e8712aa/OpenCore%20EFI%20(10.15-11)/EFI/OC/config.plist#L882)
