### ISSUE TITLE
Readme tips

### ISSUE THREAD

**Issue by rakbladsvalsen** [joepool/Hackintosh-HP-Z420-OpenCore#2]
Just installed Big Sur Beta with your EFI folder, thank you Joepool. However, I'd like to point out some things that might be worth including in your readme: 

1) Installing without PCIe expansion cards
Since the default USB controller is crap, you'll often end up with a "Still waiting for root device..."  and installer will be stuck at this point with a prohibition symbol in the center of the screen.  This can be solved by plugging the USB installer into another (2.0) port. You need to do this whenever you see either the prohibition symbol or the "Still waiting [...]". Literally spent hours because of this.

2) SSDT-GPU-SPOOF
This can be safely removed from your config.plist (RX 580 works just fine) However, I think it would be better to remove this from your config.plist since some Z420 units ship with different GPUs. Mine came with a 4000, so the SSDT spoof wouldn't have worked. It might as well be better to create a list of SSDTs for unsupported GPUs, such as Quadro 4000/K4000, but that would be up to you. 

Other than that, this works just fine. Thank you.

**Comment by joepool** [comment]
Thank you for these suggestions, I have modified my readme to mention these issues. Glad you got your Z420 up and running.
