### ISSUE TITLE
Installer gets stuck at Ethernet [IntelMausi]

### ISSUE THREAD

**Issue by wbreiler** [joepool/Hackintosh-HP-Z420-OpenCore#3]
The installer USB gets stuck at _Ethernet [IntelMausi]_ and freezes for a few seconds before giving me the "not permitted" symbol. I've followed the Dortania guides, but no such luck. I'm plugged into a USB 2 port, and i've tried all ports on my computer. I'm using your BIOS settings, too.
![image](https://user-images.githubusercontent.com/69875107/99917289-e749e280-2cd4-11eb-9d3a-3d2157261298.png)

**Comment by joepool** [comment]
weird, I've never seen an issue like that before. Try removing the kext (temporarily) and see if you can boot the installer. (Don't forget to remove it from the kext folder and your config.plist) If that works, and you need ethernet to setup macOS, try the AppleIntelE1000e.kext (ill add this to my repo now)

**Comment by wbreiler** [comment]
Thank you!

**Comment by wbreiler** [comment]
That didn't fix anything... :/

**Comment by wbreiler** [comment]
I changed to AppleIntelE1000e and it didn't change anything... :(

**Comment by joepool** [comment]
so you're saying that you have removed intel mausi kext from the kext folder, and your config.plist, but you are still getting an error related to intel mausi? that can't be right. Any chance you can attach a higher quality image of the error you are getting stuck on, as I can't read the one you have posted.

**Comment by wbreiler** [comment]
Here's the error once the ethernet kexts are removed in both the kexts folder and the config.plist
![image](https://user-images.githubusercontent.com/69875107/99919001-3ea18000-2ce0-11eb-84ae-2db49aa8eb5d.jpeg)

**Comment by joepool** [comment]
well that looks like a disk problem of some sort. I'm guessing you are using an nvme ssd (with a pcie adaptor or something). the second line from the bottom also suggests an install media problem (waiting on boot uuid media) does the activity light on your drive stop flashing at this point? I would suggest removing all internal drives and trying to boot the installer again. could you also give me a full list of your hardware, so I can help out better?

**Comment by wbreiler** [comment]
``` 
CPU - E5-1650v2 
RAM - 4x4GB Samsung DDR3 ECC
GPU - EVGA GTX 960
Drives - Intel Pro 2500 SATA M.2 SSD in a PCIe riser; Toshiba KXG5AZNV256G NVMe SSD in a PCIe riser; Hitachi H3D5001672S; Seagate ST1000DM003; and a Seagate ST500LM021
```
I'm trying to install High Sierra. I've removed all the internal drives, and I recreated the USB. Still no luck. And at this point, yes, the activity light on the USB does stop blinking

**Comment by joepool** [comment]
okay, I feel like this could be a gpu issue, as removing the nvme drive didn't help. have you removed the SSDT-GPU-SPOOF.aml? you could also try the `nv_disable=1` boot argument.  note that I have never tried the open core efi on anything other than Catalina and BigSur.

**Comment by wbreiler** [comment]
I removed the GPU SPOOF.aml I'll try ```nv_disable=1```.

**Comment by wbreiler** [comment]
I got a little bit further...![image](https://user-images.githubusercontent.com/69875107/99921117-e96c6b00-2ced-11eb-8e8f-7a2a43cc6337.jpeg)

**Comment by wbreiler** [comment]
Is my SMBIOS wrong? I'm using ```MacPro6,1```

**Comment by joepool** [comment]
Ah I had that error. I never actually found a way to fix it, other than starting again with my EFI following the Dortania guide for IvyBridge-E, which seemed to work. MacPro6,1 SMBIOS is working fine for me on Catalina and Big Sur, but when I was using HighSierra I also had luck with the MacPro5,1 and iMac14,2.

**Comment by wbreiler** [comment]
I was able to boot into the installer, but mouse and keyboard aren't working...

**Comment by joepool** [comment]
Is your mouse and keyboard plugged into a usb 2.0 port? usb 3.0 won’t work at all on macOS. Also, what did you have to change to get it to boot?

**Comment by wbreiler** [comment]
Mouse and kb are plugged in to a 2.0 port, yes. I'm not sure what I changed, I just made the installer again and it decided to boot 🤷

**Comment by joepool** [comment]
weird, not sure what's going on with mouse and keyboard. id suggest trying a different usb 2.0 port, or a different mouse and keyboard if you gave them.

**Comment by wbreiler** [comment]
I've tried different USB 2.0 ports, and different mice and keyboards... not sure what else to try now... :/
