### ISSUE TITLE
USB 3.0 

### ISSUE THREAD

**Issue by IrvingGuerra** [joepool/Hackintosh-HP-Z420-OpenCore#5]
Hi! I want to use USB 3.0 but im from mexico, so, the Inatek usb 3.0 expand its not here.

Could you tell me if any of these cards could help me?

https://www.amazon.com.mx/Serounder-Adaptador-expansi%C3%B3n-Interfaz-operativo/dp/B07MYSWF9X/ref=sr_1_1_sspa?__mk_es_MX=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=PCI-E+a+USB+3.0&qid=1616637643&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFINkpXUEFWVTg3UU0mZW5jcnlwdGVkSWQ9QTEwMTAzNjgxQkdVNUhZODRKTFQ4JmVuY3J5cHRlZEFkSWQ9QTAxOTA2ODcxQTZOUjg1WDdESTE1JndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

https://www.amazon.com.mx/expansi%C3%B3n-Ethernet-adaptador-sobremesa-compatible/dp/B089JYVHYR/ref=sr_1_12?__mk_es_MX=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=PCI-E+a+USB+3.0&qid=1616637643&sr=8-12

https://www.amazon.com.mx/interfaz-expansi%C3%B3n-ASHATA-adaptador-multifunci%C3%B3n/dp/B07S9D315F/ref=sr_1_7?__mk_es_MX=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=PCI-E+a+USB+3.0&qid=1616637643&sr=8-7

https://www.amazon.com.mx/JSER-Puertos-Express-Expansi%C3%B3n-Adaptador/dp/B07CVWG9BT/ref=sr_1_8?__mk_es_MX=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=PCI-E+a+USB+3.0&qid=1616637643&sr=8-8

THANKS FOR README :)

**Comment by joepool** [comment]
Hi,
The first link you sent I don't think will work, I purchased one with the same chipset and it didn't work for me. I am unsure about the other three though I'm afraid. 
[I did find this one which looks like it might work](https://www.amazon.com.mx/BEYIMEI-PCI-Express-Tarjeta-expansión-puertos/dp/B087WNWD4M/ref=sr_1_4?__mk_es_MX=ÅMÅŽÕÑ&dchild=1&keywords=Mac%2BOS%2Busb%2Bpcie&qid=1616955749&sr=8-4&th=1), However I'm not 100% sure as I haven't tested my self. 
If you wanted to try one of the 4 you linked, id recommend the second one, but again, I haven't tried it my self.
If you do end up purchasing one, let me know if it works or not and ill add it to the readme!
