### ISSUE TITLE
VoodooHDA Audio not working above macOS 11.3

### ISSUE THREAD

**Issue by IrvingGuerra** [joepool/Hackintosh-HP-Z420-OpenCore#7]
Hello!!! Its me again.

I bought a new SSD, then take the opportunity to fully upgrade.

Install BigSur and clone your EFI exactly.

Everything perfect, but I have 2 bugs ...

First the Audio does not work. It does not appear on the list.

could you help me!

By the way! Buy the exact same Inateck USB 3.0 card. And even so it does not detect the devices ...

THANK YOU

![Captura de Pantalla 2021-07-21 a la(s) 19 41 25](https://user-images.githubusercontent.com/37481550/126583194-bdbb86fa-0460-40c5-ad2b-4be24b61595a.png)

![Captura de Pantalla 2021-07-21 a la(s) 20 04 52](https://user-images.githubusercontent.com/37481550/126584613-5753295f-1dde-49f6-bf05-2ac79d7859de.png)

NOTE: I think it is my version of BigSur 11.5.

What version should I use? or is there a solution?

**NOTE2: I Fix it temporally buying this:**

![Captura de Pantalla 2021-07-23 a la(s) 19 18 11](https://user-images.githubusercontent.com/37481550/126851900-ac008cab-5715-412f-a6bf-5a681883ea11.png)

**Comment by joepool** [comment]
Hi!
Yes, I did know about the audio bug, the kext that I am using (VoodooHDA) is unsupported above BigSur 11.3, my apologies for not mentioning this in the readme. I have attempted to setup AppleALC audio kext, however the audio codec on z420 machines is proving difficult to setup with AppleALC. I will keep trying to get AppleALC, or hopefully VoodooHDA is updated soon.
Strange that your USB 3.0 card isn't working. Mine worked straight out of the box. You could try using the USBInjectAll kext and see if It works with that. If so, you may need to create a new USB Map.

**Comment by constantdev** [comment]
Thank you for sharing the information. I have the same audio issue. Hope the new voodooHDA will work. Thanks.

**Comment by BillDH2k** [comment]
For the on-board audio to work with AppleALC, you must fix the IRQ conflicts - TMR(0), PIC(2), and RTC0(8). Then ssdt audio injection (Realtek 262) will work. Just to want to pass on this information. Not trying to hijack joe's work, I have  uploaded an OC  loader with that fix. Works on both Big Sur, as well as Catalina.  

Regards!

**Comment by joepool** [comment]
Thank you @BillDH2k ! your efi looks great, I will try to get audio working with your suggestions. It also looks like you've got power management working without the use of the nullcpupowermanagement kext? Ill have to try to get that working too with my E5-1650 v2 
cheers

**Comment by BillDH2k** [comment]
You are welcome! Apple CPU Power Management will work, after the two kernel patches are applied.  Of course, the correct CPU ssdt must be provided. Use AppleIntelInfo.kext to verify if full PM is working, as shown in bilbo's guide.

**Comment by joepool** [comment]
Thanks to @BillDH2k I have got AppleALC audio working, audio should now be working above MacOS 11.3
