### ISSUE TITLE
my installer gets stuck at "2 minutes remaining" and then reboots

### ISSUE THREAD

**Issue by WeirdLizzard** [joepool/Hackintosh-HP-Z420-OpenCore#8]
![266739806_603972587559980_4902971948138732534_n](https://user-images.githubusercontent.com/96919176/147831666-60a3b4bc-ede3-438b-83e0-e2c085d0dbd4.jpg)
help i have no clue why this is
im running a xeon e5 1660 and a gtx 770

**Comment by joepool** [comment]
is your CPU an E5-1660 or an E5-1660 v2?
The 1660 is Sandy bridge, whereas the v2 is Ivy Bridge. This EFI was designed for Ivy Bridge.
Also, based on your error message, there may be a problem with the disk. Have you correctly formatted it to APFS using disk utility?

**Comment by WeirdLizzard** [comment]
> is your CPU an E5-1660 or an E5-1660 v2? The 1660 is Sandy bridge, whereas the v2 is Ivy Bridge. This EFI was designed for Ivy Bridge. Also, based on your error message, there may be a problem with the disk. Have you correctly formatted it to APFS using disk utility?

it is a sandy bridge, i found a different efi that spoofed the cpu and it now works, i can link to it if someone needed it, i figured it is because of the older gen cpu because trying to install this on unsupported macs gives the same error, thanks for the reply and for the work on this tho.
and yes i did choose apfs cuz i am running an ssd and as far as i know it requires apfs

**Comment by joepool** [comment]
Glad you got it working!
And yes you are correct, Catalina does requires APFS.
Closing this issue now, if you have anymore questions, feel free to reopen it.
