### ISSUE TITLE
A little question about CPU

### ISSUE THREAD

**Issue by Jissee** [joepool/Hackintosh-HP-Z420-OpenCore#9]
Hello! I am a fan of hackintosh and have a z420 which has almost the same hardware as yours. Your EFI file can boot macOS Big Sur on my machine smoothly. I have a question that whether my CPU(Intel Xeon E5-1620 v2) can be replaced by the one which has better performance, like E5-2680 v2?

**Comment by joepool** [comment]
Hi, sorry for the late response on this one. While theoretically this is possible yes, as they are both ivy bridge processors I can't guarantee that this CPU will work without any modifications to the EFI. There may be issues with power management etc that require changes. You will not know this until you get one of these cpus in a a machine though.
Good luck.
